name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Luau CLI
        run: |
          wget https://github.com/Roblox/luau/releases/latest/download/luau-ubuntu.zip
          unzip luau-ubuntu.zip -d luau
          chmod +x luau/luau

      - name: Run tests
        run: |
          ./luau/luau runTests.luau
